import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { DesignBrief } from "./types.ts";
import { copyAsset, ensureDir, removePath, writeTextFile } from "../utils/fs.ts";
import { parseJsonObject } from "../utils/json.ts";
import { getOpenAIClient } from "../utils/openai.ts";

type GeneratedFile = {
  path: string;
  content: string;
};

type GeneratedWebsiteBundle = {
  files: GeneratedFile[];
};

const REQUIRED_BASE_FILES = ["index.html", "about.html", "contact.html", "styles.css", "script.js"] as const;
const COPIED_ASSET_FILES = new Set(["assets/logo.svg", "assets/brand-lockup.svg"]);

function normalizePath(path: string): string | null {
  const normalized = path.replace(/\\/g, "/").replace(/^\.?\//, "").trim();
  if (!normalized || normalized.startsWith("/") || normalized.includes("..")) return null;
  return normalized;
}

function nonEmptyText(value: unknown): string | null {
  return typeof value === "string" && value.trim() ? value : null;
}

function sanitizeBundle(value: unknown): GeneratedWebsiteBundle | null {
  const input = value as { files?: unknown };
  if (!Array.isArray(input.files)) return null;

  const files: GeneratedFile[] = [];
  const seen = new Set<string>();
  for (const item of input.files) {
    const file = item as { path?: unknown; content?: unknown };
    const path = typeof file.path === "string" ? normalizePath(file.path) : null;
    const content = nonEmptyText(file.content);
    if (!path || !content || seen.has(path)) return null;
    seen.add(path);
    files.push({ path, content });
  }

  return files.length ? { files } : null;
}

function extractTitle(html: string): string | null {
  return html.match(/<title>\s*([^<]+?)\s*<\/title>/i)?.[1]?.trim() || null;
}

function extractMetaDescription(html: string): string | null {
  return (
    html.match(/<meta\s+name=["']description["']\s+content=["']([^"']+)["'][^>]*>/i)?.[1]?.trim() ||
    html.match(/<meta\s+content=["']([^"']+)["']\s+name=["']description["'][^>]*>/i)?.[1]?.trim() ||
    null
  );
}

function hasBEMSelector(css: string): boolean {
  return /\.[a-z][a-z0-9-]*__[a-z0-9-]+/.test(css);
}

function includesPageLink(html: string, file: string): boolean {
  const escaped = file.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`href=["'](?:\\./)?${escaped}(?:#[^"']*)?["']`, "i").test(html);
}

function includesAssetReference(html: string, assetPath: string): boolean {
  const escaped = assetPath.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  return new RegExp(`(?:src|href)=["'](?:\\./)?${escaped}["']`, "i").test(html);
}

function hasUnsafeSvgHref(content: string): boolean {
  const hrefPattern = /\s(?:href|xlink:href)=["']([^"']+)["']/gi;
  for (const match of content.matchAll(hrefPattern)) {
    const target = match[1]?.trim();
    if (!target?.startsWith("#")) return true;
  }
  return false;
}

function hasUnsafeSvgUrl(content: string): boolean {
  const urlPattern = /url\(\s*["']?([^"')\s]+)["']?\s*\)/gi;
  for (const match of content.matchAll(urlPattern)) {
    const target = match[1]?.trim();
    if (!target?.startsWith("#")) return true;
  }
  return false;
}

function validateSvg(path: string, content: string, errors: string[]): void {
  if (!/<svg[\s\S]*<\/svg>/i.test(content)) errors.push(`${path} must contain a complete SVG document.`);
  if (/<script|<foreignObject|<image|\son\w+=/i.test(content) || hasUnsafeSvgHref(content) || hasUnsafeSvgUrl(content)) {
    errors.push(`${path} contains disallowed SVG content.`);
  }
}

function validateWebsiteBundle(bundle: GeneratedWebsiteBundle, brief: DesignBrief): string[] {
  const errors: string[] = [];
  const files = new Map(bundle.files.map((file) => [file.path, file.content]));
  const requiredFiles = brief.uxPlan.projectsContact.hasProjectPortfolio
    ? [...REQUIRED_BASE_FILES, "projects.html"]
    : [...REQUIRED_BASE_FILES];
  const allowedRootFiles = new Set<string>(requiredFiles);

  for (const file of requiredFiles) {
    if (!files.has(file)) errors.push(`Missing required file: ${file}.`);
  }

  if (brief.uxPlan.projectsContact.hasProjectPortfolio && !files.has("projects.html")) {
    errors.push("Portfolio businesses must include projects.html.");
  }
  if (!brief.uxPlan.projectsContact.hasProjectPortfolio && files.has("projects.html")) {
    errors.push("Non-portfolio businesses must not include projects.html.");
  }

  for (const [path, content] of files) {
    if (COPIED_ASSET_FILES.has(path)) {
      errors.push(`${path} is copied from the selected brand assets and must not be generated by OpenAI.`);
    } else if (path.startsWith("assets/")) {
      if (!/^assets\/[a-z0-9][a-z0-9-]*\.svg$/i.test(path)) {
        errors.push(`${path} is not an allowed generated asset path.`);
      } else {
        validateSvg(path, content, errors);
      }
    } else if (!allowedRootFiles.has(path)) {
      errors.push(`${path} is not an allowed root output file.`);
    }
  }

  const htmlFiles = requiredFiles.filter((file) => file.endsWith(".html"));
  const titles = new Set<string>();
  const descriptions = new Set<string>();
  for (const file of htmlFiles) {
    const html = files.get(file) || "";
    if (!/<!doctype html>/i.test(html)) errors.push(`${file} must start with an HTML5 doctype.`);
    if (!/<html[\s>]/i.test(html) || !/<main[\s>]/i.test(html)) errors.push(`${file} must contain semantic HTML.`);
    if (!/<link[^>]+href=["']\.?\/?styles\.css["'][^>]*>/i.test(html)) {
      errors.push(`${file} must link to styles.css.`);
    }
    if (!/<script[^>]+src=["']\.?\/?script\.js["'][^>]*><\/script>/i.test(html)) {
      errors.push(`${file} must load script.js.`);
    }
    if (!includesAssetReference(html, "assets/logo.svg")) {
      errors.push(`${file} must visibly include the selected standalone logo asset at ./assets/logo.svg.`);
    }
    if (!includesAssetReference(html, "assets/brand-lockup.svg")) {
      errors.push(`${file} must visibly include the selected typography lockup asset at ./assets/brand-lockup.svg.`);
    }
    for (const linkedFile of htmlFiles) {
      if (!includesPageLink(html, linkedFile)) errors.push(`${file} navigation must link to ${linkedFile}.`);
    }
    const title = extractTitle(html);
    const description = extractMetaDescription(html);
    if (!title) errors.push(`${file} must include a title.`);
    if (!description) errors.push(`${file} must include a meta description.`);
    if (title) titles.add(title.toLowerCase());
    if (description) descriptions.add(description.toLowerCase());
  }
  if (titles.size !== htmlFiles.length) errors.push("Every HTML page must have a unique title.");
  if (descriptions.size !== htmlFiles.length) errors.push("Every HTML page must have a unique meta description.");

  const css = files.get("styles.css") || "";
  if (!hasBEMSelector(css)) errors.push("styles.css must include BEM-style component selectors.");
  if (!/@media\b/i.test(css)) errors.push("styles.css must include responsive media queries.");
  for (const color of brief.brand.palette) {
    if (!css.toLowerCase().includes(color.toLowerCase())) {
      errors.push(`styles.css must visibly use selected palette color ${color}.`);
    }
  }

  const script = files.get("script.js") || "";
  if (/https?:\/\/|fetch\s*\(|XMLHttpRequest|sendBeacon|import\s*\(/i.test(script)) {
    errors.push("script.js must be local-only and must not call remote services.");
  }

  return errors;
}

async function readWebsiteSpec(): Promise<string> {
  try {
    return await readFile("WEBSITE.md", "utf8");
  } catch {
    throw new Error("Frontend website generation requires WEBSITE.md in the project root.");
  }
}

function bundlePrompt(
  brief: DesignBrief,
  websiteSpec: string,
  previousBundle?: GeneratedWebsiteBundle,
  errors?: string[],
): string {
  const requiredPages = brief.uxPlan.projectsContact.hasProjectPortfolio
    ? "index.html, about.html, projects.html, contact.html"
    : "index.html, about.html, contact.html";
  const repair =
    previousBundle && errors?.length
      ? `\nRepair this previously invalid bundle. Fix every validation error and return the complete corrected bundle, not a patch.\nValidation errors:\n${errors
          .map((error) => `- ${error}`)
          .join("\n")}\nPrevious bundle:\n${JSON.stringify(previousBundle, null, 2)}\n`
      : "";

  return `${repair}
Create the final static website files for this generated brand. Return only valid JSON with this exact shape:
{
  "files": [
    {"path": "index.html", "content": "..."},
    {"path": "about.html", "content": "..."},
    {"path": "contact.html", "content": "..."},
    {"path": "styles.css", "content": "..."},
    {"path": "script.js", "content": "..."}
  ]
}

Required root files: ${requiredPages}, styles.css, script.js.
Allowed generated asset files: assets/*.svg. Do not include assets/logo.svg or assets/brand-lockup.svg because those are copied from selected brand assets after generation.

Design brief:
${JSON.stringify(brief, null, 2)}

Website specification:
${websiteSpec}

Generation rules:
- Make the pages feel designed for this specific business, not like a generic repeated template.
- Use distinct page compositions and section layouts while keeping shared navigation and footer consistent.
- Use the selected palette exactly in CSS: ${brief.brand.palette.join(", ")}.
- Every HTML page must visibly use both copied brand assets: the standalone logo at ./assets/logo.svg and the typography/name lockup at ./assets/brand-lockup.svg.
- Place both brand assets in the shared header brand area, or place one in the header and the other in the footer/hero, but both must appear on every HTML page.
- Size and style both brand assets so they are plainly visible on desktop and mobile; do not hide either asset with filters, opacity, clipping, zero dimensions, display:none, or color-inverting styles that erase contrast.
- Include business-aligned SVG placeholders under assets/ when imagery or icons are needed.
- Generated SVG placeholders may use inline shapes, gradients, masks, symbols, and internal fragment references like href="#shape", but must not reference external files or URLs.
- Keep all links local. Do not load remote fonts, scripts, stylesheets, images, analytics, or APIs.
- Use semantic HTML5, unique page titles and descriptions, responsive layout, accessible buttons/forms, and BEM-style CSS class names.
- Include hamburger navigation behavior in script.js.
- If there is no portfolio page, include capabilities on the Home page and do not invent fake projects.
- If there is a portfolio page, use the AI UX plan's project copy and include a contact call to action.
- Return the complete file bundle every time.`;
}

async function generateBundle(
  brief: DesignBrief,
  previousBundle?: GeneratedWebsiteBundle,
  errors?: string[],
): Promise<GeneratedWebsiteBundle> {
  const client = await getOpenAIClient();
  if (!client?.responses) {
    throw new Error(
      "Frontend website generation requires OpenAI. Set OPENAI_API_KEY, run npm install, and ensure the model returns a valid website file bundle.",
    );
  }

  const response = await client.responses.create({
    model: process.env.SITEGEN_FRONTEND_MODEL || process.env.OPENAI_MODEL || "gpt-5.5",
    instructions:
      "You are a senior frontend engineer building polished static corporate websites. Return only valid JSON. Do not use Markdown.",
    input: bundlePrompt(brief, await readWebsiteSpec(), previousBundle, errors),
  });

  if (!response.output_text) throw new Error("OpenAI returned no frontend website bundle text.");
  const bundle = sanitizeBundle(parseJsonObject(response.output_text));
  if (!bundle) throw new Error("OpenAI returned an invalid frontend website bundle shape.");
  return bundle;
}

async function generateValidatedBundle(brief: DesignBrief): Promise<GeneratedWebsiteBundle> {
  const firstBundle = await generateBundle(brief);
  const firstErrors = validateWebsiteBundle(firstBundle, brief);
  if (!firstErrors.length) return firstBundle;

  const repairedBundle = await generateBundle(brief, firstBundle, firstErrors);
  const repairedErrors = validateWebsiteBundle(repairedBundle, brief);
  if (!repairedErrors.length) return repairedBundle;

  throw new Error(`OpenAI returned an invalid frontend website bundle after repair:\n${repairedErrors.join("\n")}`);
}

async function writeBundle(bundle: GeneratedWebsiteBundle, webDir: string): Promise<void> {
  await Promise.all(
    bundle.files.map((file) =>
      writeTextFile(join(webDir, file.path), file.content.endsWith("\n") ? file.content : `${file.content}\n`),
    ),
  );
}

export async function generateStaticSite(brief: DesignBrief): Promise<string> {
  const webDir = join("dist", "web");
  const assetsDir = join(webDir, "assets");
  const bundle = await generateValidatedBundle(brief);

  await removePath(webDir);
  await ensureDir(assetsDir);
  await writeBundle(bundle, webDir);
  await copyAsset(brief.brand.lockupPath, join(assetsDir, "brand-lockup.svg"));
  await copyAsset(brief.brand.logoPath, join(assetsDir, "logo.svg"));
  await readFile(join(webDir, "index.html"), "utf8");
  return webDir;
}
